### ISSUE TITLE
Unable to use cudnn (GPU) 

### ISSUE THREAD

**Issue by sundeeptewari** [mitmul/ssai-cnn#20]
I am using the following code for training URL : https://github.com/mitmul/ssai-cnn
My Environment specifications are given below:
Xeon CPU, 128 GB RAM
nVidia  TITAN Xp Graphics Card 
Driver Version 384.90
CUDA 9.0, CUDNN 7.0

Ubuntu 16.04, Anaconda3 Environment on python 3.5.1
chainer     1.5.0.2           
cupy        2.0.0             
curl        7.55.1 
boost       1.65.1            
Cython      0.27.3            
h5py        2.7.1             
hdf5        1.10.1            
lmdb        0.87              
matplotlib  2.1.0             
numpy       1.13.3            
opencv      3.3.0           
pillow      4.3.0             
pycuda      2017.1.1          
python      3.5.1             
six         1.11.0           
tqdm        4.19.4

I am running the training process on dataset of 430 images (Resolution 1500X1500 pixels)
CUDNN is configured cuda.cudnn_enabled gives True
Training doesn’t run fine in CPU environment . While using GPU environment using the flag CHAINER_CUDNN = 0  (i.e. cudnn disabled) it gives warning message about cudnn and the GPU usage shows only max. 25%. I feel it is not utilizing the GPU environment fully during training as 1 EPOCH takes 2-3 hrs on average, assuming this for 400 epochs it would take us too many 800-1200hrs (33-50 days) to complete the training.
+++ Warning message showing CuDNN not enabled for training+++
 /home/user/anaconda3/envs/ssai-cnn/lib/python3.5/site-packages/chainer/cuda.py:85: UserWarning: cuDNN is not enabled.
Please reinstall chainer after you install cudnn
(see https://github.com/pfnet/chainer#installation).
  'cuDNN is not enabled.\n'
++++++++++++++++++++++++++++++++++++++++++++++++++++++

When I tried to run the training process using cudnn  (i.e. CHAINER_CUDNN = 1)  then it gives error.
+++++ Error message +++++++
2017-12-08 11:36:34 INFO     start training...
2017-12-08 11:36:34 INFO     learning rate:0.0005
2017-12-08 11:36:34 INFO     random skip:2
Traceback (most recent call last):
  File "/common/workspace/ssai-cnn/src/scripts/train.py", line 373, in <module>
    model, optimizer = one_epoch(args, model, optimizer, epoch, True)
  File "/common/workspace/ssai-cnn/src/scripts/train.py", line 285, in one_epoch
    optimizer.update(model, x, t)
  File "/home/user/anaconda3/envs/ssai-cnn/lib/python3.5/site-packages/chainer/optimizer.py", line 377, in update
    loss = lossfun(*args, **kwds)
  File "/common/workspace/ssai-cnn/src/models/MnihCNN_multi.py", line 22, in __call__
    h = F.relu(self.conv1(x))
  File "/home/user/anaconda3/envs/ssai-cnn/lib/python3.5/site-packages/chainer/links/connection/convolution_2d.py", line 74, in __call__
    return convolution_2d.convolution_2d(x, self.W, self.b, self.stride, self.pad, self.use_cudnn)
  File "/home/user/anaconda3/envs/ssai-cnn/lib/python3.5/site-packages/chainer/functions/connection/convolution_2d.py", line 267, in convolution_2d
    return func(x, W, b)
  File "/home/user/anaconda3/envs/ssai-cnn/lib/python3.5/site-packages/chainer/function.py", line 105, in __call__
    outputs = self.forward(in_data)
  File "/home/user/anaconda3/envs/ssai-cnn/lib/python3.5/site-packages/chainer/function.py", line 181, in forward
    return self.forward_gpu(inputs)
  File "/home/user/anaconda3/envs/ssai-cnn/lib/python3.5/site-packages/chainer/functions/connection/convolution_2d.py", line 80, in forward_gpu
    (self.ph, self.pw), (self.sy, self.sx))
TypeError: create_convolution_descriptor() missing 1 required positional argument: 'dtype'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I just want to confirm if your process had run on cudnn enabled mode is yes then what chainer and cupy and other supporting package versions were used?
What will be the challenges on existing code if I have to upgrade the Chainer version 3.0.0 or 3.1.0 , Cupy 2.1.0 and other packages? Which chainer-cupy version combination will be preferable?

Thanks

**Comment by thiagodsti** [comment]
He used the Chainer 1.5.0.2

I couldn't training using my GPU too and how i'm using hyperface for my university term paper i'll have to implement this again upgrading the chainer version.

I had the same problems that you are having right now. =/

He left a already trained network to use, so if you just want to check how it works you could use that.
https://github.com/mitmul/ssai-cnn#pre-trained-models-and-predicted-results

**Comment by mitmul** [comment]
@sundeeptewari @thiagodsti 
Thank you for trying my code. Could you uninstall CuPy first? And then please try the supported CUDA and cuDNN versions. Chainer 1.5.0.2 supports only CUDA 6.5, 7.0, and 7.5, and cuDNN v2 and v3. Please check this [README of Chainer v1.5](https://github.com/chainer/chainer/tree/c91fe82b51b4eab6593bb3c06b2bc92706abc4b9) for more details. If you want to keep your current CUDA environment unchanged, I think the easiest way to setup such environment is to use NVIDIA Docker. It can make a container that includes CUDA 7.5 and cuDNN v3. Please check this Dockerfile: [7.5-cudnn3-devel](https://gitlab.com/nvidia/cuda/blob/ubuntu14.04/7.5/devel/cudnn3/Dockerfile). This should enable to make a sufficient environment to use this code. Thanks.

**Comment by mitmul** [comment]
Here's a Dockerfile created by @Skylion007: https://github.com/mitmul/ssai-cnn/pull/5

**Comment by Avery1991** [comment]
@sundeeptewari @mitmul @thiagodsti  
Hi, friends. Sorry to disturb you.  
Recently I got some troubles in compiling the environment which can make the codes run. Could you please tell me your cmake version?
Thank you so much for your kindly help and time.
